### ISSUE TITLE
Add Carousel

### ISSUE THREAD

**Issue by joshuabitforce** [joshuabitforce/bitforce#5]
Create a Carousel that will show a container with two equal sides. One for the text, and the other with an image

![Image](https://github.com/joshuabitforce/bitforce/assets/141953271/ad03f16b-4f37-45d6-a452-022449017cc1)

**Comment by bruchus** [comment]
@joshuabitforce I've also replaced React icons for ours, removed commented text in index.html, and changed object-fit to cover for img component.
